# Callback Data Prefixes
CALLBACK_MARK_DONE = "done_"
CALLBACK_DELETE_REMINDER = "delrem_"
CALLBACK_NOOP = "noop_"
CALLBACK_SELECT_HABIT_DELETE = "seldelhab_"
CALLBACK_CONFIRM_DELETE_HABIT = "confdelhab_"
CALLBACK_CANCEL_DELETE = "canceldel_"
CALLBACK_SELECT_REMINDER_HABIT = "setremhab_"
CALLBACK_HISTORY_PAGE = "histpg_"
CALLBACK_SELECT_HABIT_DONE = "seldone_"
CALLBACK_SELECT_HABIT_EDIT = "seledithab_"
CALLBACK_EDIT_FIELD_PREFIX = "editfld_" # e.g., editfld_name_{id}
CALLBACK_CANCEL_EDIT = "canceledit_"
CALLBACK_YES = "yes_"
CALLBACK_NO = "no_"

# Conversation States (Ranges)
ADD_HABIT_STATES = range(3)
ASK_NAME, ASK_DESCRIPTION, ASK_CATEGORY = ADD_HABIT_STATES
SET_REMINDER_STATES = range(2)
SELECT_REMINDER_HABIT, ASK_REMINDER_TIME = SET_REMINDER_STATES
DELETE_HABIT_STATES = range(2)
ASK_HABIT_TO_DELETE, CONFIRM_DELETE = DELETE_HABIT_STATES
EDIT_HABIT_STATES = range(4)
SELECT_HABIT_TO_EDIT, SELECT_FIELD_TO_EDIT, ASK_NEW_VALUE, CONFIRM_EDIT_SAVE = EDIT_HABIT_STATES

# Job Names
JOB_PREFIX_REMINDER = "reminder_" # reminder_{user_id}_{habit_id}

# Command Names
CMD_START = "start"
CMD_HELP = "help"
CMD_ADD_HABIT = "add_habit"
CMD_TODAY = "today"
CMD_DONE = "done"
CMD_HISTORY = "history"
CMD_STATS = "stats"
CMD_SET_REMINDER = "set_reminder"
CMD_MANAGE_REMINDERS = "manage_reminders"
CMD_DELETE_HABIT = "delete_habit"
CMD_EDIT_HABIT = "edit_habit"
CMD_CANCEL = "cancel"
CMD_REFRESH_MEMBERSHIP = "refresh_membership"

# Misc
HISTORY_PAGE_LIMIT = 15