# Callbacks
CALLBACK_MARK_DONE = "d_"
CALLBACK_DELETE_REMINDER = "dr_"
CALLBACK_NOOP = "noop_"
CALLBACK_SELECT_HABIT_DELETE = "sdh_"
CALLBACK_CONFIRM_DELETE_HABIT = "cdh_"
CALLBACK_CANCEL_DELETE = "cd_"
CALLBACK_SELECT_REMINDER_HABIT = "srh_"
CALLBACK_HISTORY_PAGE = "hp_"
CALLBACK_SELECT_HABIT_DONE = "sdd_"
CALLBACK_SELECT_HABIT_EDIT = "seh_"
CALLBACK_EDIT_FIELD_PREFIX = "ef_" # e.g., ef_name_{id}
CALLBACK_CANCEL_EDIT = "ce_"
CALLBACK_YES = "y_"
CALLBACK_NO = "n_"

# Convo States
ADD_HABIT_STATES = range(3); ASK_NAME, ASK_DESCRIPTION, ASK_CATEGORY = ADD_HABIT_STATES
SET_REMINDER_STATES = range(2); SELECT_REMINDER_HABIT, ASK_REMINDER_TIME = SET_REMINDER_STATES
DELETE_HABIT_STATES = range(2); ASK_HABIT_TO_DELETE, CONFIRM_DELETE = DELETE_HABIT_STATES
EDIT_HABIT_STATES = range(4); SELECT_HABIT_TO_EDIT, SELECT_FIELD_TO_EDIT, ASK_NEW_VALUE, CONFIRM_EDIT_SAVE = EDIT_HABIT_STATES

# Jobs
JOB_PREFIX_REMINDER = "rem_" # rem_{user_id}_{habit_id}

# Commands
CMD_START = "start"; CMD_HELP = "help"; CMD_ADD_HABIT = "add_habit"; CMD_TODAY = "today"; CMD_DONE = "done"
CMD_HISTORY = "history"; CMD_STATS = "stats"; CMD_SET_REMINDER = "set_reminder"
CMD_MANAGE_REMINDERS = "manage_reminders"; CMD_DELETE_HABIT = "delete_habit"; CMD_EDIT_HABIT = "edit_habit"
CMD_CANCEL = "cancel"; CMD_REFRESH_MEMBERSHIP = "refresh_membership"

# Misc
HISTORY_PAGE_LIMIT = 15